--- Sentencias SQL para la creación del esquema de el hotel andes

-- USO
-- Copie el contenido deseado de este archivo en una pestaña SQL de SQL Developer
-- Ejecútelo como un script - Utilice el botón correspondiente de la pestaña utilizada
    
-- Eliminar todas las tablas de la base de datos
DROP TABLE EMPLEADOS CASCADE CONSTRAINTS;
DROP TABLE GASTOS CASCADE CONSTRAINTS;
DROP TABLE HABITACIONES CASCADE CONSTRAINTS;
DROP TABLE GASTOS CASCADE CONSTRAINTS;
DROP TABLE RESERVAS CASCADE CONSTRAINTS;
DROP TABLE CLIENTES CASCADE CONSTRAINTS;
DROP TABLE PLANES_DE_CONSUMO CASCADE CONSTRAINTS;
DROP TABLE SERVICIOS_HOTELES CASCADE CONSTRAINTS;
DROP TABLE HOTELES CASCADE CONSTRAINTS;
DROP TABLE TIPOS_RESERVA_HABITACION CASCADE CONSTRAINTS;
DROP TABLE TIPOS_IDENTIFICACION CASCADE CONSTRAINTS;
DROP TABLE TIPOS_PLAN_DE_CONSUMOS CASCADE CONSTRAINTS;
DROP TABLE TIPOS_ROL CASCADE CONSTRAINTS;
COMMMIT;

